/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import negocio.bo.EstudianteBo;
import negocio.bo.LibroBo;
import negocio.bo.ProfesorBo;
import negocio.bo.ReservaEstudianteBo;
import negocio.clases.Estudiante;
import negocio.clases.Libro;
import negocio.clases.Profesor;
import negocio.clases.ReservaEstudiante;
import negocio.clases.ReservaProfesor;

/**
 *
 * @author enzoq
 */
public class MantReservaEstudiante extends javax.swing.JFrame {

    ReservaEstudianteBo rebo;
    EstudianteBo ebo;
    LibroBo lbo;

    /**
     * Creates new form MantReservaProfesor
     */
    public MantReservaEstudiante() {

        this.ebo = new EstudianteBo();
        this.lbo = new LibroBo();
        this.rebo = new ReservaEstudianteBo();

        initComponents();
        fillStudents();
        fillBooks();
    }

    public void fillStudents() {
        List<Estudiante> list = getEbo().getAll();
        this.jComboBoxEstudiante.addItem("---Seleccione estudiante---");
        for (Estudiante e : list) {
            this.jComboBoxEstudiante.addItem(e.getCedula() + "-" + e.getNombre());
        }
    }

    public void fillBooks() {
        List<Libro> list = getLbo().getAll();
        this.jComboBoxLibro.addItem("---Seleccione libro---");
        for (Libro lb : list) {
            this.jComboBoxLibro.addItem(lb.getCodigo() + "-" + lb.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxEstudiante = new javax.swing.JComboBox<>();
        jComboBoxLibro = new javax.swing.JComboBox<>();
        spDias = new javax.swing.JSpinner();
        addButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Reservas de estudiantes");

        jLabel2.setText("Estudiante: ");

        jLabel3.setText("Días: ");

        jLabel4.setText("Libro: ");

        jComboBoxEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstudianteActionPerformed(evt);
            }
        });

        spDias.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        addButton.setText("Agregar reserva");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxLibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spDias)
                                .addComponent(jComboBoxEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(spDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(addButton)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (validateData()) {
            ReservaEstudiante ire = new ReservaEstudiante();

            String profe = this.jComboBoxEstudiante.getSelectedItem().toString();
            String[] partesProfe = profe.trim().split("-");
            ire.setCedulaEstudiante(Integer.parseInt(partesProfe[0]));

            String libro = this.jComboBoxLibro.getSelectedItem().toString();
            String[] partesLibro = libro.trim().split("-");
            ire.setCodigoLibro(Integer.parseInt(partesLibro[0]));

            ire.setDiasPrestamo((Integer) spDias.getValue());
            ire.setFecha(new Date());

            getRebo().insert(ire);

        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void jComboBoxEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstudianteActionPerformed

    private boolean validateData() {
        if (jComboBoxEstudiante.getSelectedIndex() == 0) {
            showJOptionPane("Seleccione un profesor");
            return false;
        }
        if (jComboBoxLibro.getSelectedIndex() == 0) {
            showJOptionPane("Seleccione un libro");
            return false;
        }
        return true;
    }

    private void showJOptionPane(String string) {
        JOptionPane.showMessageDialog(null, string);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantReservaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantReservaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantReservaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantReservaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantReservaEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addButton;
    private javax.swing.JComboBox<String> jComboBoxEstudiante;
    private javax.swing.JComboBox<String> jComboBoxLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spDias;
    // End of variables declaration//GEN-END:variables

    public ReservaEstudianteBo getRebo() {
        return rebo;
    }

    public EstudianteBo getEbo() {
        return ebo;
    }

    public void setEbo(EstudianteBo ebo) {
        this.ebo = ebo;
    }

    public LibroBo getLbo() {
        return lbo;
    }

    public void setLbo(LibroBo lbo) {
        this.lbo = lbo;
    }

}
